[package]
name = "jvm"
version = "0.1.0"
authors = ["Ben Wyatt <googleben@sbcglobal.net>"]

[dependencies]
java_class = { path = "../java_class" }
log = "0.4.0"
env_logger = "0.9.0"
zip = "0.5"
va_list = "0.1.3"