[package]
name = "class_browser"
version = "0.1.0"
authors = ["Ben Wyatt <googleben@sbcglobal.net>"]

[dependencies]
glib = "=0.14.0"
gtk = { version = "0.14.0" }
gdk-pixbuf = "0.14.0"
java_class = { path = "../java_class" }

[profile.release]
opt-level = 3